# Generated by Django 2.1.3 on 2019-05-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('provideing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.serviceCategory')),
                ('providing_services', models.ManyToManyField(to='client.subServiceCategory')),
            ],
        ),
    ]
