# Generated by Django 2.1.4 on 2018-12-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'company')], default='M', max_length=2)),
                ('services_done_count', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_rating', models.FloatField(blank=True, null=True)),
                ('push_id', models.CharField(blank=True, max_length=20)),
                ('profile_description', models.CharField(max_length=300)),
                ('address', models.TextField(blank=True, help_text='json encoded', max_length=10000)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos_provider/')),
                ('is_activted', models.BooleanField(default=False)),
                ('token', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.token')),
            ],
        ),
        migrations.CreateModel(
            name='providerComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('owner', models.ForeignKey(on_delete='', to='provider.provider')),
                ('to', models.ForeignKey(on_delete='', to='client.user')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='skillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
                ('joined_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.subServiceCategory')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.skillTag'),
        ),
    ]
