# Generated by Django 2.1.3 on 2019-05-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='providing_services',
        ),
        migrations.AlterField(
            model_name='provider',
            name='provideing_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.subServiceCategory'),
        ),
    ]
