# Generated by Django 2.1.3 on 2019-05-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('provider', '0002_auto_20190516_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='providing_services',
            field=models.ManyToManyField(to='client.subServiceCategory'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provideing_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.serviceCategory'),
        ),
    ]
