# Generated by Django 2.1.3 on 2019-05-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('provider', '0003_auto_20190516_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='provideing_category',
        ),
        migrations.AddField(
            model_name='provider',
            name='providing_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='client.serviceCategory'),
            preserve_default=False,
        ),
    ]
