# Generated by Django 2.1.3 on 2019-05-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_availabledatetimeservice_service'),
        ('provider', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='availableDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.ManyToManyField(to='client.availableDateTimeService')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
    ]
