# Generated by Django 2.1.3 on 2019-05-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_availabledates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='providing_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='client.serviceCategory'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='providing_services',
            field=models.ManyToManyField(related_name='provides', to='client.subServiceCategory'),
        ),
    ]
