# Generated by Django 2.1.3 on 2019-05-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20190525_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='provider_images/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
